#ifndef ANONYMOUSOBJECT_H
#define ANONYMOUSOBJECT_H

#include "../Object/Object.h"

#define ANONYMOUS_OBJECT_NAME __ANONYMOUS_OBJECT__

#define ANONYMOUS_OBJECT___GENERATED_CLASS_NAME CONCAT(__ANONYMOUS_OBJECT__, __COUNTER__)

#define ANONYMOUS_OBJECT___CONST_CLASS_NAME ANONYMOUS_OBJECT___GENERATED_CLASS_NAME

#define CONST_STRING_ANONYMOUSE_NAME const char * anonymousObjectClassName;

Object *createAnonymousObject();

#endif //ANONYMOUSOBJECT_H
