name: Publish

on:
  push:
    tags:
      - '*-release'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src/oop/oop.a
          asset_name: oop.a
          tag: ${{ github.ref }}
          overwrite: true
          body: "oop.a static library"
