name: Publish

on:
  push:
    tags:
      - '*-release'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*.md"
        tags: true
        draft: true
